Update main.yml
hopefully the last + versioning

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,17 +24,20 @@ jobs:
         DEBUG: "true"
 
     - name: Check if build output directory exists
-    run: |
-      if [ ! -d "/Neos yt-dlp Updater/bin/Release/net6.0" ]; then
-        echo "Build output directory not found"
-        exit 1
-      fi
+      run: |
+        if [ ! -d "bin/Release/net6.0" ]; then
+          echo "Build output directory not found"
+          exit 1
+        fi
+
+    - name: Set version based on current year, day, and time
+      run: echo "::set-env name=VERSION::$(date +'%Y.%j.%H%M')"
 
     - name: Zip the built files
-      run: zip -r Release.zip bin/Release/net6.0/*
+      run: zip -r Release-${{ env.VERSION }}.zip bin/Release/net6.0/*
 
     - name: Upload the release artifact
       uses: actions/upload-artifact@v2
       with:
         name: Release
-        path: ./Release.zip
+        path: ./Release-${{ env.VERSION }}.zip
